Backup/SVTrade/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SVTrade.Controllers
{
    public class HomeController : Controller
    {
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }


        [Authorize] // This is for Authorize user
        public ActionResult MyProfile()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        public ActionResult AdminIndex()
        {
            return View();
        }



        [Authorize(Roles = "User")]
        public ActionResult UserIndex()
        {
            return View();
        }



        [Authorize(Roles = "Manager")]
        public ActionResult ManagerIndex()
        {
            return View();
        }



        [Authorize(Roles = "ConfirmedUser")]
        public ActionResult ConfirmedUserIndex()
        {
            return View();
        }

    }
}

Backup/SVTrade/Controllers/RegistrationController.cs
using System.Linq;
using System.Web.Mvc;
using SVTrade.Abstract;
using SVTrade.Models;
using System.Collections.Generic;
using System;
using System.Text;
using System.Security.Cryptography;
using System.Web.Security;

namespace SVTrade.Controllers
{
    public class UserRegistrationController : Controller
    {
        private IRepository repository;


        public UserRegistrationController(IRepository repo)
        {
            repository = repo;
        }






        [HttpGet]
        public ActionResult Register()
        {
            List<SelectListItem> listSelectListItems = new List<SelectListItem>();

            foreach (ProductCategory city in repository.ProductCategories)
            {
                SelectListItem selectList = new SelectListItem()
                {
                    Text = city.name,
                    Value = city.productCategoryID.ToString(),

                };
                listSelectListItems.Add(selectList);
            }

            Register citiesViewModel = new Register()
            {
                Cities = listSelectListItems
            };

            return PartialView(citiesViewModel);
        }




        [HttpPost]
        public string Register(User user, IEnumerable<string> selectedCities)
        {
            StringBuilder sb = new StringBuilder();
            if (selectedCities == null)
            {
                sb.Append("No cities are selected");
            }
            else
            {

                sb.Append(string.Join("", selectedCities));

                if (ModelState.IsValid)
                {
                    var crypto = new SimpleCrypto.PBKDF2();
                    var encrpass = crypto.Compute(user.password);                     
                    user.password = encrpass; 
                    User user2 = null;
                    user2 = repository.Users.Where(u => u.email == user.email || u.password == user.password || u.companyName == user.companyName).FirstOrDefault();
                    if (user2 == null)
                    {
                        user.passwordSalt = crypto.Salt;
                        user.merchantLicense = false;
                        user.tradeLicense = false;
                        user.userGroupID = 3;
                        repository.SaveUser(user);
                        foreach (string item in selectedCities)
                        {
                            ChoosedCategory ck = new ChoosedCategory();
                            ck.userID = user.userID;
                            ck.productCategoryID = Convert.ToInt32(item);
                            repository.SaveChoosedCategory(ck);
                        }



                        ModelState.Clear();
                        ViewBag.Message = "Реєстрація прошла успішно!";


                    }
                    else
                    {
                        ModelState.AddModelError(" ", "Користувач уже існує!");
                        ViewBag.Message = "Користувач уже існує!";
                    }

                }
                else
                {
                    ViewBag.Message = "Перевірте поля!";


                }



            }
            RedirectToAction("Index");
            return sb.ToString();
        }



       
    }
}

Backup/SVTrade/Views/Home/About.cshtml
@{
    ViewBag.Title = "Як це працює";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- ******Why Section****** -->
<section class="section why">
    <div class="container">
        <p class="top-pad big-text text-center">Як це працює?</p>
        <div class="row item">
            <div class="content col-md-8 col-sm-12 col-xs-12">
                <h3 class="title">Крок 1</h3>
                <div class="desc">
                    <p>
                        Зареєструйтесь на нашому сайті, під час реєстрації вкажіть в ролі покупця чи продавця ви бажаєте приймати участь в проекті.
                        Під час реєстарції вкажіть які саме категорії товарів вас цікавлять.
                    </p>
                    <div class="quote">
                        <div class="quote-content">
                            <blockquote><p>Також ви також можете виступати в обох ролях одночасно.</p></blockquote>
                        </div><!--//quote-content-->
                    </div><!--//quote-->
                </div>
            </div><!--//content-->
            <figure class="figure col-md-4 col-sm-12 col-xs-12">
                <div class="icon-space">
                    <div class="window">
                        <p class="counter">1</p>
                    </div>
                    <div class="helper"></div>
                </div>
                <figcaption class="figure-caption">Крок 1 </figcaption>
            </figure>
        </div><!--//item-->

        <div class="row item">
            <div class="content col-md-8 col-sm-12 col-xs-12">
                <h3 class="title">Крок 2</h3>
                <div class="desc">
                    <p>Зачекайте, доки наш менеджер зв'яжиться з вами для підтвердження інформації про ваш профіль.</p>
                    <div class="quote">
                        <div class="quote-content">
                            <blockquote><p>Після підтвердження в вашому профілі з'явиться лізензія продавця або покупця.</p></blockquote>
                        </div><!--//quote-content-->
                    </div><!--//quote-->
                </div>
            </div><!--//content-->
            <figure class="figure col-md-4 col-sm-12 col-xs-12">
                <div class="icon-space">
                    <div class="window">
                        <p class="counter">2</p>
                    </div>
                    <div class="helper"></div>
                </div>
                <figcaption class="figure-caption">Крок 2 </figcaption>
            </figure>
        </div><!--//item-->

        <div class="row item">
            <div class="content col-md-8 col-sm-12 col-xs-12">
                <h3 class="title">Крок 3</h3>
                <div class="desc">
                    <p>Перейдіть на сторінку пошуку товарів для здійснення покупок, або в власний кабінет для додвання товарів на сайт.</p>
                    <div class="quote">
                    </div><!--//quote-->
                </div>
            </div><!--//content-->
            <figure class="figure col-md-4 col-sm-12 col-xs-12">
                <div class="icon-space">
                    <div class="window">
                        <p class="counter">3</p>
                    </div>
                    <div class="helper"></div>
                </div>
                <figcaption class="figure-caption">Крок 3 </figcaption>
            </figure>
        </div><!--//item-->
    </div><!--//container-->
</section><!--//why-->

<aside class="footer">
    <div class="container text-center">
        <div class="call-to-action">
            <h2>Наші контакти</h2>
        </div>
    </div>
</aside>

<!-- ******FOOTER****** -->
<section class="footer">
    <div id="contact" class="footer-content">
        <div class="container">
            <div class="row has-divider">
                <div class="footer-col connect col-md-6 col-sm-12 col-xs-12">
                    <div class="footer-col-inner">
                        <ul class="social list-inline">
                            <li><a href="https://twitter.com/EnergoKyznya" target="_blank"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="https://www.facebook.com/energokuznya"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="http://vk.com/public95055356"><i class="fa fa fa-vk"></i></a>
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                            <li><a href="https://www.youtube.com/channel/UCIYORbd53e8ylT6at3pxNVQ"><i class="fa fa-youtube-square"></i></a></li>
                            <li class="row-end"><a href="#"><i class="fa fa-rss"></i></a></li>
                        </ul>
                        <div class="form-container">
                            <p class="intro">Залишайтесь в курсі останніх новин від Енерго Кузні</p>
                            <form class="signup-form navbar-form">
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="example@email.com">
                                </div>
                                <button type="submit" class="btn btn-ghost">Підписатись</button>
                            </form>
                        </div><!--//subscription-form-->
                    </div><!--//footer-col-inner-->
                </div><!--//foooter-col-->
                <div class="footer-col connect col-md-6 col-sm-12 col-xs-12">
                    <div class="footer-col-inner">
                        <ul class="social list-inline">
                            <li><a href="https://twitter.com/EnergoKyznya" target="_blank"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="https://www.facebook.com/energokuznya"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="http://vk.com/public95055356"><i class="fa fa fa-vk"></i></a>
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                            <li><a href="https://www.youtube.com/channel/UCIYORbd53e8ylT6at3pxNVQ"><i class="fa fa-youtube-square"></i></a></li>
                            <li class="row-end"><a href="#"><i class="fa fa-rss"></i></a></li>
                        </ul>
                        <div class="form-container">
                            <p class="intro">Залишайтесь в курсі останніх новин від Unknown Data</p>
                            <form class="signup-form navbar-form">
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="example@email.com">
                                </div>
                                <button type="submit" class="btn btn-ghost">Підписатись</button>
                            </form>
                        </div><!--//subscription-form-->
                    </div><!--//footer-col-inner-->
                </div><!--//foooter-col-->
                <div class="clearfix"></div>
            </div><!--//row-->
            <div class="row has-divider">
                <div class="footer-col contact col-md-6 col-sm-12 col-xs-12">
                    <div class="footer-col-inner left-map">
                        <h3 class="title">Unknown Data</h3>
                        <p class="adr clearfix">
                            <i class="fa fa-map-marker pull-left"></i>
                            <span class="adr-group pull-left">
                                <span class="street-address">Unknown Data</span><br>
                                <span class="region">Unknown Data</span><br>
                                <span class="postal-code">Unknown Data.</span><br>
                                <span class="country-name">Unknown Data</span>
                            </span>
                        </p>
                        <p class="tel"><i class="fa fa-phone"></i>Unknown Data</p>
                        <p class="tel"><i class="fa fa-phone"></i>Unknown Data</p>
                        <p class="tel"><i class="fa fa-phone"></i>Unknown Data</p>
                        <p class="email"><i class="fa fa-envelope-o"></i><a href="#">Unknown Data</a></p>
                        <a href="https://twitter.com/Unknown Data" class="twitter-follow-button" data-show-count="false">Follow Unknown Data</a>
                        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
                    </div><!--//footer-col-inner-->
                </div><!--//contact-->
                <div class="footer-col contact col-md-6 col-sm-12 col-xs-12">
                    <div class="footer-col-inner">
                        <iframe class="map-frame" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d20301.506874771214!2d30.238645972244267!3d50.50275762939976!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x472b33c3adf5b61b%3A0x408c1787c24ceafe!2z0LLRg9C7LiDQm9GW0YHQvtCy0LAsIDE5LCDQhtGA0L_RltC90YwsINCa0LjRl9Cy0YHRjNC60LAg0L7QsdC70LDRgdGC0YwsINCj0LrRgNCw0LjQvdCw!5e0!3m2!1sru!2s!4v1438209192495" width="585" height="265" frameborder="1" style="border:1"></iframe>
                    </div><!--//footer-col-inner-->
                </div><!--//contact-->
            </div>
        </div><!--//container-->
    </div><!--//footer-content-->
</section><!--//footer-->

Backup/SVTrade/Views/Home/AdminIndex.cshtml
@{
    ViewBag.Title = "AdminIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AdminIndex</h2>

@{
    ViewBag.Title = "AdminIndex";
}


<div>Welcome @(Request.IsAuthenticated ? HttpContext.Current.User.Identity.Name : "") (Admin)</div>

Backup/SVTrade/Views/Home/ConfirmedUserIndex.cshtml
@{
    ViewBag.Title = "ConfirmedUserIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ConfirmedUserIndex</h2>


<div>Welcome @(Request.IsAuthenticated ? HttpContext.Current.User.Identity.Name : "") (ConfirmedUserIndex)</div>

Backup/SVTrade/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
 Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    <h2>@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>
    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>
    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</div>

Backup/SVTrade/Views/Home/Index.cshtml
@{
    ViewBag.Title = "СВ Трейд Холод";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<header class="">
    <div class="blured"></div>
    <div class="header-content">
        <div class="container">
            <div class="row">
                <p class="big-text">СВ Трейд Холод </p>
                <p class="">Пропонує вам тисячі тон готової продукції онлайн дозволяють заощадити ваш час та гроші!</p>
                <ul class="list-inline">
                    <li>Тільки свіжа продукція</li>
                    <li>Тільки перевірена якість</li>
                    <li>Всі економлять час та гроші</li>
                </ul>
            </div>
            <div class="row smtop-pad">
                <div class="col-md-6 col-sm-12 col-xs-12">
                    <div class="">
                        <ul class="social list-inline">
                            <li><a href="https://twitter.com/EnergoKyznya" target="_blank"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="https://www.facebook.com/energokuznya"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="http://vk.com/public95055356"><i class="fa fa fa-vk"></i></a>
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                            <li><a href="https://www.youtube.com/channel/UCIYORbd53e8ylT6at3pxNVQ"><i class="fa fa-youtube-square"></i></a></li>
                            <li class="row-end"><a href="#"><i class="fa fa-rss"></i></a></li>
                        </ul>
                        <div class="form-container">
                            <p class="intro">Отримуйте останні новини від СВ Трейд Холод</p>
                            <form class="signup-form navbar-form">
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="example@email.com">
                                </div>
                            </form>
                        </div><!--//subscription-form-->
                    </div><!--//footer-col-inner-->
                </div><!--//foooter-col-->
                <div class="col-md-6 col-sm-12 col-xs-12">
                    <div class="idf">
                        @Html.ActionLink("Реєстрація", "Register", "UserRegistration", new { area =""}, htmlAttributes: new { id = "registerLink", @class = "logs btn btn-ghost" })
                    </div>
                    <div class="idf">
                        @Html.ActionLink("Увійти", "Login", "Account", new { area =""}, htmlAttributes: new { id = "loginLink", @class = "logs btn btn-ghost" })
                    </div><!--//subscription-form-->
                </div><!--//footer-col-inner-->
            </div><!--//foooter-col-->
            <div class="clearfix"></div>
        </div><!--//row-->
    </div>
</header>

Backup/SVTrade/Views/Home/ManagerIndex.cshtml
@{
    ViewBag.Title = "ManagerIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ManagerIndex</h2>

 
 
<div>Welcome @(Request.IsAuthenticated ? HttpContext.Current.User.Identity.Name : "") (ManagerIndex)</div>

Backup/SVTrade/Views/Home/MyProfile.cshtml
@{
    ViewBag.Title = "MyProfile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>MyProfile</h2>

<h3>Welcome @(Request.IsAuthenticated ? HttpContext.Current.User.Identity.Name : "Guest") - This is for Authorized user </h3>

Backup/SVTrade/Views/Home/UserIndex.cshtml
@{
    ViewBag.Title = "UserIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

 

<h2>User Index</h2>
<div>Welcome @(Request.IsAuthenticated ? HttpContext.Current.User.Identity.Name : "")  (User) </div>